services:
  page:
    container_name: landing-page
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
      - NOTION_MILESTONES_DATABASE_ID=${NOTION_MILESTONES_DATABASE_ID}
